version: '3.1'
services:
  stats-server:
    build: ./statistics-service/service
    image: statistics-server-image
    container_name: statistics-server-cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=exploreWithMe
      - DB_HOST=stats-db
      - DB_PORT=5432
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=exploreWithMe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"


  ewm-service:
    build: ./main-service
    image: main-server-image
    container_name: main-server-cont
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=exploreWithMeMain
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    depends_on:
      - stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=exploreWithMeMain
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"