#server:
#  port: 9090
#
#service:
#  uri: http://localhost:9090
#
#spring:
#  mvc:
#    format:
#      local-date-time: "yyyy-MM-dd HH:mm:ss"
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL10Dialect
#        format_sql: true
#  sql:
#    init:
#      mode: always
#
#datasource:
#  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/exploreWithMe
#  username: postgres
#  password: 123123
#
## Use the following properties if you want to use environment variables instead of hardcoding the values
## datasource:
##   driverClassName: org.postgresql.Driver
##   url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
##   username: ${POSTGRES_USER}
##   password: ${POSTGRES_PASSWORD}
#
#javax:
#  persistence:
#    schema-generation:
#      database:
#        action: create
#      create-script-source: schema.sql
#
##server:
##  servlet:
##    encoding:
##      charset: UTF-8
##      force: true
